%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hauke\Desktop\CDI trade
%    analysis\GTAP_full_database\census.xlsx Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/20 20:55:30

%% Import the data
[~, ~, census1] = xlsread('census.xlsx','Sheet1','A1:B228');
census1(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),census1)) = {''};

